# Global configuration
[global]
# The root entities you want to export.
# Root entities have their own entries in the index
# You don't need to export entities which exist only
# in the context of another entity (example : paragraph)
root_entities = ['node', 'taxonomy_term', 'user']

# Entity types
# Map entity types to exporter classes
[entities.node]
exporter = 'Drupal\emigrate\Exporter\Entity\Node'

[entities.taxonomy_term]
exporter = 'Drupal\emigrate\Exporter\Entity\TaxonomyTerm'

[entities.user]
exporter = 'Drupal\emigrate\Exporter\Entity\User'

[entities.comment]
exporter = 'Drupal\emigrate\Exporter\Entity\Comment'

[entities.paragraph]
exporter = 'Drupal\emigrate\Exporter\Entity\Paragraph'

# Fields
# Map fields types to exporter classes
[fields._default]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\DefaultField'

[fields.entity_reference]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\EntityReference'

[fields.text_with_summary]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\TextWithSummary'

[fields.comment]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\Comment'

[fields.image]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\Image'

[fields.link]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\Link'

[fields.entity_reference_revisions]
exporter = 'Drupal\emigrate\Exporter\BaseFieldDefinition\EntityReferenceRevisions'
