# Map entity types to exporters
# Example : Drupal nodes will be processed
# by exporter \Drupal\emigrate\Facade\Entity\Node
# Backslashes in namespace must be escaped with a second backslash

[global]
# The root entities you want to export.
# Root entities have their own entry in the index
# You don't need to export entities which exists only
# in the context of another entity (example : paragraph)
root_entities = ['node', 'taxonomy_term', 'user']

# Entity types
# Map entity types to exporter classes
[entity.node]
exporter = "\\Drupal\\emigrate\\Facade\\Entity\\Node"

[entity.taxonomy_term]
exporter = "\\Drupal\\emigrate\\Facade\\Entity\\TaxonomyTerm"

[entity.user]
exporter = "\\Drupal\\emigrate\\Facade\\Entity\\User"


[entity.comment]
exporter = "\\Drupal\\emigrate\\Facade\\Entity\\Comment"

[entity.paragraph]
exporter = "\\Drupal\\emigrate\\Facade\\Entity\\Paragraph"

# Fields
# Map fields types to exporter classes
[entity.base_field]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\DefaultField"

[entity.field_config.entity_reference]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\EntityReference"

[entity.field_config.text_with_summary]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\TextWithSummary"

[entity.field_config.comment]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\Comment"

[entity.field_config.image]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\Image"

[entity.field_config.link]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\Link"

[entity.field_config.entity_reference_revisions]
exporter = "\\Drupal\\emigrate\\Facade\\BaseFieldDefinition\\EntityReferenceRevisions"

[entity]
# Map a bundle to a specific exporter
# This exporter will override the entity one listed above

# Example
# [entity.node.bundle.article]
# exporter ="\\Drupal\\emigrate\\Facade\\Entity\\MyExporter"
